### ISSUE TITLE
Blur effect - UWP

### ISSUE THREAD

**Issue by Depechie** [FormsCommunityToolkit/Effects#8]
Current implementation of the Blur effect needs Win2D, need to see if we can't refactor to only target Windows Composition framework ( newer way to do UI transitions and effects ).

**Comment by jassmith** [comment]
You can't ;)

However a thought occurs for the bug with this effect you might try. In the OnAttached callback, try setting the Width/Height of the target element (the native one, not the forms one) to a size, like 10x10 or something, and then setting it back to what it was to start with.

This should force apply the effect. I think, in theory... without side effects even... maybe...

**Comment by Depechie** [comment]
Haaa, good point! Will investigate more, thanks!

**Comment by skendrot** [comment]
Why can you not use composition?

**Comment by jassmith** [comment]
I might be wrong, but I'd be surprised since I actually wrote this based on conversations and sample code directly from the composition team. My understanding is the composition layer simply doesn't have the API's required to do the blur behind. I think long term this will be available but it's not possible at the moment. Even once it is, backwards compatible support will be required.

**Comment by skendrot** [comment]
What do you mean by "blur behind"?

**Comment by bartlannoeye** [comment]
This issue was moved to FormsCommunityToolkit/FormsCommunityToolkit#9
